# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Virtual Internship
author: Pantelis Monogioudis, Ph.D
copyright: "2023"  # Copyright year to be placed in the footer
logo: ./logo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off' #cache
  timeout: 3600 #seconds
  stdout_output: show
  stderr_output: show
  allow_errors: false
  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
  exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]


# Information about where the book exists on the web
repository:
  url: https://github.com/pantelis/virtual-internship  # Online location of your book
  path_to_book: virtual-internship  # Optional path to your book, relative to the repository root
  #branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ./logo.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  baseurl: https://pantelis.github.io/virtual-internship

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  thebe: true 

sphinx:
  recursive_update: true
  config:
    html_theme: sphinx_book_theme
    bibtex_reference_style: author_year  # or label, super, \supercite
    nb_merge_streams: true
    nb_execution_show_tb: true
    html_sidebars: {"artificial_intelligence/*": []} #sbt-sidebar-nav.html
    html_theme_options:
      use_download_button: true
      repository_url: https://github.com/pantelis/artificial-intelligence
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      show_navbar_depth: 0
    intersphinx_mapping:
      python:
        - "https://docs.python.org/3/"
        - null
      numpy:
        - "https://numpy.org/doc/stable/"
        - null
      pandas:
        - "https://pandas.pydata.org/docs/"
        - null
      scikit-learn:
        - "https://scikit-learn.org/stable/"
        - null
      torch:
        - "https://pytorch.org/docs/master/"
        - null
      tf2:
        - "https://pytorch.org/docs/master/"
        - null
    language: en
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    latex_elements:
      preamble: | 
        \newcommand\N{\mathbb{N}}
        \newcommand\floor[1]{\lfloor#1\rfloor}
        \newcommand{\bmat}{\left[\begin{array}}
        \newcommand{\emat}{\end{array}\right]}
        \DeclareMathOperator*{\arg \max}{argmax}
        \DeclareMathOperator*{\argmin}{argmin}
    
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
  
  extra_extensions:
    # - sphinx_press_theme
    - sphinxcontrib.youtube
    - sphinx_inline_tabs
    - sphinxcontrib.inkscapeconverter
    #- sphinx_click.ext
    - sphinx_inline_tabs
    - sphinxext.rediraffe
    - sphinx_proof
    - sphinxcontrib.mermaid
    - sphinxcontrib.seqdiag
    #- sphinx_examples
    # - nbsite.pyodide
    #- jupyterlite_sphinx

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - deflist
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution